#! /bin/bash
if [ "$1" == "-c" ]; then
  /etc/psiphon/psiphon-tunnel-core-x86_64 -config "$2"
elif [ "$1" == "-s" ]; then
  if [ -z "$2" ]; then
    config_file="/etc/psiphon/us.config"
  else
    case "$2" in
      "FR") config_file="/etc/psiphon/fr.config" ;;
      "US") config_file="/etc/psiphon/us.config" ;;
      "UK") config_file="/etc/psiphon/uk.config" ;;
      "NL") config_file="/etc/psiphon/nl.config" ;;
      *) echo "Invalid country code. Please use US, UK, or NL." ; exit 1 ;;
    esac
  fi
  /etc/psiphon/psiphon-tunnel-core-x86_64 -config "$config_file"
else
  echo "Invalid option. Please use -c for config file address  or -s for select base config file ( US , UK , NL ) with a country code."
  exit 1
fi